export struct TemperatureInfo {
    min: float,
    max:float,

    morning: float,
    day: float,
    evening:float,
    night:float,
}

export struct WeatherInfo {
    description: string,
    icon_source: string,
    current_temp: float,
    detailed_temp: TemperatureInfo,
    uv: int,
    precipitation_prob: float,
    rain: float,
    snow: float,
}

export struct WeatherForecastInfo {
    day_name: string,
    weather_info: WeatherInfo,
}

export struct CityWeatherInfo {
    city_name: string,
    current_weather: WeatherInfo,
    forecast_weather: [WeatherForecastInfo],
    update_time: string,
}

export global CityWeather {
    in property <[CityWeatherInfo]> city-weather;

    pure callback delete(int);
    pure callback reorder(int, int);
    pure callback get_forecast_graph_command([WeatherForecastInfo], int, length, length) -> string;
}
